version: '3'

services:
  # Service MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: jerem
        MONGO_INITDB_ROOT_PASSWORD: not24get
        MONGO_INITDB_DATABASE: archi_db
    networks:
      - archi_network
    ports:
        - 27017:27017
    volumes:
      - ./archi-db-init.js:/docker-entrypoint-initdb.d/archi-db-init.js:ro

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - archi_network
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: jerem
      ME_CONFIG_MONGODB_ADMINPASSWORD: not24get
      ME_CONFIG_MONGODB_URL: mongodb://jerem:not24get@mongodb:27017/

  # Services Node.js
  nodejs:
    image: node:18.17.1
    container_name: archi_web_app
    working_dir: /back
    volumes:
      - ./back:/back
      - C:/ArchiWeb/Files:/back/ArchiWeb/Files
    networks:
      - archi_network
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    links:
      - "mongodb:mongodb"
    command: sh -c 'echo "PORT=\"3000\"" > .env && echo "DB=\"mongodb://jerem:not24get@mongodb:27017/archi_db?retryWrites=true&w=majority\"" >> .env && echo "FOLDER_FILES=\"./ArchiWeb/Files\"" >> .env && npm i && npm start'

  frontend:
    image: node:18.17.1
    container_name: frontend_app
    working_dir: /front
    volumes:
      - ./front:/front
    ports:
      - "8080:8080"
    command: sh -c "npm i && echo 'PORT=8080' > .env && npm start"

  # Service Jenkins
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins_app
    ports:
      - "8082:8080"
      - "50000:50000"

networks:
  archi_network:
    driver: bridge
