version: '3'

services:
  # Services Node.js
  nodejs:
    image: node:18.17.1
    container_name: archi_web_app
    working_dir: /back
    volumes:
      - ./back:/back
    ports:
      - "3000:3000"
    command: sh -c "npm i && echo 'PORT=3000' > .env && npm start"
    
  frontend:
    image: node:18.17.1
    container_name: frontend_app
    working_dir: /front
    volumes:
      - ./front:/front
    ports:
      - "8080:8080"
    command: sh -c "npm i && echo 'PORT=8080' > .env && npm start"

  # Service MongoDB
  mongodb:
    image: mongo:latest
    container_name: my_mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: jerem
      MONGO_INITDB_ROOT_PASSWORD: not24get
      MONGO_INITDB_DATABASE: archi_db
    ports:
      - "27017:27017"
  
  # Service Jenkins
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins_app
    ports:
      - "8081:8080"
      - "50000:50000"