version: '3'

services:
  # Service Node.js
  nodejs:
    image: node:18.17.1
    container_name: archi_web_app
    working_dir: /back
    volumes:
      - ./back:/back
    ports:
      - "3000:3000"
    command: npm run start

  frontend:
    image: node:18.17.1
    container_name: frontend_app
    working_dir: /front
    volumes:
      - ./front:/front
    ports:
      - "8080:8080"
    command: npm start

  # Service MongoDB
  mongodb:
    image: mongo:latest
    container_name: my_mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: jerem
      MONGO_INITDB_ROOT_PASSWORD: not24get
      MONGO_INITDB_DATABASE: archi_db
    ports:
      - "27017:27017"