version: '3'

services:
  # Service Node.js
  nodejs:
    image: node:18.17.1
    container_name: archi_web_app
    working_dir: /back
    volumes:
      - ./back:/back
    ports:
      - "3000:3000"
    command: sh -c "echo 'PORT=3000 DB=mongodb://localhost:27017archi_db' > .env && npm start"
    

  frontend:
    image: node:18.17.1
    container_name: frontend_app
    working_dir: /front
    volumes:
      - ./front:/front
    ports:
      - "8080:8080"
    command: sh -c "echo 'PORT=8080 DB=mongodb://jerem:not24get@127.0.0.1:27017/?authSource=admin' > .env && npm start"

  # Service MongoDB
  mongodb:
    image: mongo:latest
    container_name: my_mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: jerem
      MONGO_INITDB_ROOT_PASSWORD: not24get
      MONGO_INITDB_DATABASE: archi_db
    ports:
      - "27017:27017"